language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t steve-j-hunt/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true steve-j-hunt/docker-react npm run test -- --coverage
